version: '2'
services:

  postgres:
    image: postgres:10
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: youtube_service
      POSTGRES_PASSWORD: abc@1234
      POSTGRES_DB: youtube_service
    volumes:
      - ./create_local_db.sql:/docker-entrypoint-initdb.d
    networks:
      - api_default

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    networks:
      - api_default
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: postgres:5432

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    networks:
      - api_default
    environment:
      WAIT_HOSTS: postgres:5432

networks:
  api_default:
    external: false